# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e41654ad431265c9533c277a0c92baff"
name = "alterpop-importer"
application_url = "https://alterpop-importer-app.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/create"
  topics = [ "orders/create" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locations,read_orders,read_products,read_publications,write_inventory,write_products,write_publications"

[auth]
redirect_urls = [
  "https://alterpop-importer-app.fly.dev/auth/callback",
  "https://alterpop-importer-app.fly.dev/auth/shopify/callback"
]
