# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b8beed550d16a006068ca696bc4bf74f"
name = "alterpop-importer"
application_url = "https://growth-duty-workflow-deposits.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locations,read_orders,read_products,write_inventory,write_products"

[auth]
redirect_urls = [ "https://growth-duty-workflow-deposits.trycloudflare.com/auth/callback" ]
