/**
 * Lista curada de franquias para a grelha de /pages/franquias no tema.
 *
 * Decisão de 2026-08-15: o campo CatalogProduct.franchises vem direto da
 * categorização do fornecedor OcioStock em espanhol ("MODA Y COMPLEMENTOS",
 * "PAPELERIA", "ESCOLAR", "HIGIENE"...) — não é uma lista de franquias, é a árvore de
 * categorias do catálogo. Usá-lo diretamente pôs "Papelaria / Escolar" na grelha
 * pública lado a lado com "Marvel". Esta lista, fornecida manualmente, substitui essa
 * fonte: é fixa, não deriva de dados do fornecedor.
 *
 * Fornecida pelo Carlos a 2026-08-15 (96 nomes únicos — a lista original tinha 100,
 * com 4 repetidos: Stranger Things, Gremlins, Pokémon, Minecraft).
 */
export const FRANCHISE_CATALOG_NAMES = [
  "One Piece",
  "Dragon Ball",
  "Naruto",
  "Demon Slayer",
  "Jujutsu Kaisen",
  "My Hero Academia",
  "Chainsaw Man",
  "Spy × Family",
  "Tokyo Revengers",
  "Haikyu!!",
  "Bleach",
  "Attack on Titan",
  "Hunter × Hunter",
  "Death Note",
  "Fullmetal Alchemist",
  "Fairy Tail",
  "Black Clover",
  "Boruto",
  "JoJo's Bizarre Adventure",
  "One Punch Man",
  "Sailor Moon",
  "Saint Seiya",
  "Evangelion",
  "Cowboy Bebop",
  "Inuyasha",
  "Tokyo Ghoul",
  "Kaiju No. 8",
  "Frieren",
  "Dandadan",
  "Sakamoto Days",
  "Sand Land",
  "That Time I Got Reincarnated as a Slime",
  "Tamagotchi",
  "Yu-Gi-Oh!",
  "Beyblade",
  "Pokémon",
  "Hello Kitty",
  "Sanrio",
  "My Melody",
  "Pusheen",
  "Totoro / Studio Ghibli",
  "Stitch / Lilo & Stitch",
  "Disney",
  "Mickey Mouse",
  "Minnie Mouse",
  "Frozen",
  "Moana",
  "Toy Story",
  "The Lion King",
  "Loki",
  "The Simpsons",
  "Stranger Things",
  "Wednesday",
  "The Walking Dead",
  "Game of Thrones",
  "House of the Dragon",
  "The Witcher",
  "The Lord of the Rings",
  "The Hobbit",
  "Jurassic World",
  "Jurassic Park",
  "Gremlins",
  "Beetlejuice",
  "The Grinch",
  "Ghostbusters",
  "Back to the Future",
  "Godzilla",
  "King Kong",
  "Alien",
  "Predator",
  "The Nightmare Before Christmas",
  "Marvel",
  "Spider-Man",
  "Avengers",
  "Captain America",
  "Fantastic Four",
  "Iron Man",
  "Deadpool",
  "Batman / DC",
  "Superman",
  "Harley Quinn",
  "Star Wars",
  "Harry Potter",
  "Super Mario",
  "Sonic the Hedgehog",
  "Minecraft",
  "Five Nights at Freddy's",
  "The Legend of Zelda",
  "Nintendo",
  "Fallout",
  "Fortnite",
  "League of Legends",
  "Monster Hunter",
  "Assassin's Creed",
  "Final Fantasy",
  "Kingdom Hearts",
];
